### ISSUE TITLE
Where's the change jar?

### ISSUE THREAD

**Issue by frankstallone** [ouun/stage#204]
I have been looking for a long time for some modern framework to put my hat on with regards to WordPress theme development, and this might just be it. I am new to `root/sage` but need to get up and running with a client site. I know this is in beta, and will be battle testing, but this is the closets I have seen anyone get to my goals. I had this setup with Lando in almost no time. Your direction with regards to Tailwind are the right direction. I read the entire thread on the Sage Discourse forums, could not reply to you there, and could not find any other way to reach out to you (Twitter/Discord/Slack) so I came here, to the root (no pun intended). As I get more familiar with this mix of web technologies, I hope I can contribute to this. I have not seen many changes, the last in November, I hope you have not given up on this project! If I can contribute in a monetary, please share with me where the tip jar is.

**Comment by ouun** [comment]
hi @frankstallone,
thanks for your feedback. I am happy if it is useful for others. The main goal still is to get some devs to contribute so that we have a more feature rich starting point. But as you read already, it seems the interest is not that high.
However I have not had much time to continue working on Stage, on the same time I just release another client project that is based on Stage as Parent Theme (alpha.14) and uses the [Stage Child Theme](https://github.com/ouun/stage-child/) to customize every aspect. Just made the Child-Repo public for you, so you can use it. 

To get an idea of how that could work:
Get the latest release stage.zip, it includes most functionality, basic styles and some JS as seen in the repo but is already comiled. Add it to WordPress as Parent Theme. Next you clone the Child next to the parent and start to extend / customize that. 

Feel free to test it and to open PR's if you find something to improve. You could also skip the parent/child separation and just clone Stage and work on that. But please keep in mind that this is a very early state and I am absolutely unsure when I will have time to work on it. So another option is to use [regular Sage](https://roots.io/sage) and to get some inspiration from here. And if you still want to throw  something in the tip jar, [here](https://www.paypal.com/paypalme/ouun) you go. :)

**Comment by frankstallone** [comment]
Since your last reply I decided I needed to see how much I could do on my own to have a better idea of what you have layered on top here. First, you are a much better developer than I am with regards to organizing your custom code in PHP, and I love your rationale/decisions in the JS diretion. 

I attempted to pull the work you did for the PhotoSwipe plugin. I followed your paradigm, or architecture making small modifications here and there where needed. I couldn't get it work on the first try. Kept getting empty `<body>` elements in the browser when trying to load with the new changes. 

This tells me I need to keep digging. I think the principals you have put into place here are _fantastic_. Your folder structures for organization, your comments and practices are above mine. I am a rusty WordPress developer, Sage is already so much newer than I am used to working with and I am more used to the NodeJS. 

I have not had a chance to look at the child theme yet but I already know that's the right direction to keep Sage up to date. This is a stepping stone for me to get more comfortable with the changes y'all have made here and be more useful.

I also want to say the more I work with Sage the more I see this is the direction I want to go in with WordPress theming. 🥇 Happy Friday!

**Comment by Dioniggio** [comment]
Hello guys, this Roots Sage extension is very interesting, I inspected the code and I like how is organized. I will give a try in my next project. I think is a good starting point, better than starting from blank Sage 10, I like the idea of putting some JS tools that are common in theme development projects. It gives a nice guide to put your own code/files.

I hope this gets popular and devs collaborate improving it. In my case, I'm not sure if I can collaborate with you, my dev level isnt good enough tho. I'll try to propose improvements and features.

And here's the first one: 

CPT registering using https://github.com/log1x/poet and have a starting point to register CPT, another common feature in WP Theme projects in my opinion.

@ouun Please try to make this project visible in https://discourse.roots.io/ to recruit some good devs!

Regards!

**Comment by ouun** [comment]
Thanks for your positive feedback @Dioniggio. And please feel free to promote the idea further in the community. 
Poet is definatly awesome and I am using it a lot, too. You can just add it to your Stage project as you would for Sage.
